### ISSUE TITLE
Double metaphone code is limited to 4 characters only

### ISSUE THREAD

**Issue by anilyayavar** [aravind-j/PGRdup#3]
Both the primary and alternate codes in DoubleMetaphone are limited to 4 characters.  Shouldn't these be included in full?

**Comment by aravind-j** [comment]
`DoubleMetaphone` adapts Maurice Aubrey's perl module hosted at the [gitpan/Text-DoubleMetaphone](https://github.com/gitpan/Text-DoubleMetaphone/blob/master/double_metaphone.c) which limits the primary and alternate codes to 4 characters. It can be included in full by changing the limits in [fdouble_metaphone.c](https://github.com/aravind-j/PGRdup/blob/3fd3d7a2f7e424d8aaae2319cb1c2a6316c1a5d1/src/fdouble_metaphone.c#L1439C1-L1443C28).
